// src/controllers/qr.controller.ts
import { Context } from "hono";
import { createDb, type Env } from "../db";
import { locations } from "../db/schema";
import { eq } from "drizzle-orm";
import { CryptoHelper } from "../utils/crypto.helper";
import { NotificationHelper } from "../utils/notification.helper";

export class QRController {
  /**
   * Generate QR Code untuk presensi (check-in atau check-out)
   * Role: Admin only
   */
  static async generate(c: Context<{ Bindings: Env }>) {
    const user = c.get("user");
    const locationId = c.req.param("locationId");
    const qrType = c.req.query("type") || "check_in"; // 'check_in' atau 'check_out'
    const db = createDb(c.env.DB);
    const cryptoHelper = new CryptoHelper(c.env);

    try {
      // Validasi location exists
      const [location] = await db
        .select()
        .from(locations)
        .where(eq(locations.id, Number(locationId)))
        .limit(1);

      if (!location) {
        return c.json(
          {
            success: false,
            message: "Location not found",
          },
          404,
        );
      }

      // Validasi QR type
      if (!["check_in", "check_out"].includes(qrType)) {
        return c.json(
          {
            success: false,
            message: 'Invalid QR type. Must be "check_in" or "check_out"',
          },
          400,
        );
      }

      // Generate random token (32 characters)
      const token = cryptoHelper.generateRandomToken(32);

      // Data yang disimpan di KV
      const qrData = {
        locationId: locationId,
        locationName: location.name,
        type: qrType,
        generatedBy: user.id,
        generatedByName: user.name,
        timestamp: new Date().toISOString(),
        expiresIn: 600, // seconds
      };

      // Simpan ke KV dengan TTL 600 detik
      await c.env.KV.put(`qr:${token}`, JSON.stringify(qrData), {
        expirationTtl: 600, // 600 detik
      });

      // Generate QR code URL menggunakan external API
      const qrCodeData = JSON.stringify({
        token: token,
        type: qrType,
        location_id: locationId,
      });

      const qrImageUrl = `https://api.qrserver.com/v1/create-qr-code/?data=${encodeURIComponent(qrCodeData)}&size=300x300&format=png`;

      // Kirim notifikasi ke semua employee (opsional)
      try {
        const notificationHelper = new NotificationHelper(c.env);
        await notificationHelper.broadcastQRGenerated(location.name, qrType);
      } catch (error) {
        console.error("Failed to send QR notification:", error);
        // Don't fail if notification fails
      }

      // Log aktivitas (bisa disimpan ke table activity_logs jika ada)
      console.log(
        `QR Code generated by ${user.name} (${user.id}) for ${location.name} - Type: ${qrType}`,
      );

      return c.json({
        success: true,
        message: "QR Code generated successfully",
        data: {
          token: token,
          type: qrType,
          location: {
            id: location.id,
            name: location.name,
          },
          generated_by: {
            id: user.id,
            name: user.name,
          },
          qr_code_url: qrImageUrl,
          qr_data: qrCodeData,
          expires_in: 600,
          expires_at: new Date(Date.now() + 600000).toISOString(),
          usage_instructions: `Scan QR code within 600 seconds for ${qrType === "check_in" ? "Check-in" : "Check-out"}`,
        },
      });
    } catch (error) {
      console.error("QR generation error:", error);
      return c.json(
        {
          success: false,
          message: "Internal server error",
        },
        500,
      );
    }
  }

  /**
   * Validate QR token (untuk debugging atau preview)
   * Role: All authenticated users
   */
  static async validate(c: Context<{ Bindings: Env }>) {
    const token = c.req.param("token");

    try {
      const qrData = await c.env.KV.get(`qr:${token}`);

      if (!qrData) {
        return c.json(
          {
            success: false,
            message: "Invalid or expired QR code",
          },
          400,
        );
      }

      const data = JSON.parse(qrData);
      const ttl = await c.env.KV.get(`qr:${token}`, { type: "text" });

      // Get remaining TTL (approximate)
      const generatedTime = new Date(data.timestamp).getTime();
      const currentTime = Date.now();
      const elapsedSeconds = Math.floor((currentTime - generatedTime) / 1000);
      const remainingSeconds = Math.max(0, 600 - elapsedSeconds);

      return c.json({
        success: true,
        data: {
          valid: true,
          type: data.type,
          location: {
            id: data.locationId,
            name: data.locationName,
          },
          generated_by: {
            id: data.generatedBy,
            name: data.generatedByName,
          },
          generated_at: data.timestamp,
          expires_in_seconds: remainingSeconds,
          expires_at: new Date(generatedTime + 60000).toISOString(),
        },
      });
    } catch (error) {
      console.error("QR validation error:", error);
      return c.json(
        {
          success: false,
          message: "Internal server error",
        },
        500,
      );
    }
  }

  /**
   * List active QR codes (untuk monitoring)
   * Role: Admin only
   */
  static async listActive(c: Context<{ Bindings: Env }>) {
    const user = c.get("user");

    try {
      // List all QR keys in KV
      const qrKeys = await c.env.KV.list({ prefix: "qr:" });

      const activeQRCodes = [];

      for (const key of qrKeys.keys) {
        const qrData = await c.env.KV.get(key.name);
        if (qrData) {
          const data = JSON.parse(qrData);
          const generatedTime = new Date(data.timestamp).getTime();
          const currentTime = Date.now();
          const remainingSeconds = Math.floor(
            (currentTime - generatedTime) / 1000,
          );

          activeQRCodes.push({
            token: key.name.replace("qr:", ""),
            type: data.type,
            location: data.locationName,
            generated_by: data.generatedByName,
            generated_at: data.timestamp,
            remaining_seconds: Math.max(0, 600 - remainingSeconds),
          });
        }
      }

      return c.json({
        success: true,
        data: {
          total_active: activeQRCodes.length,
          active_codes: activeQRCodes,
        },
      });
    } catch (error) {
      console.error("List active QR error:", error);
      return c.json(
        {
          success: false,
          message: "Internal server error",
        },
        500,
      );
    }
  }

  /**
   * Revoke/Delete QR code manually
   * Role: Admin only
   */
  static async revoke(c: Context<{ Bindings: Env }>) {
    const token = c.req.param("token");
    const user = c.get("user");

    try {
      const qrData = await c.env.KV.get(`qr:${token}`);

      if (!qrData) {
        return c.json(
          {
            success: false,
            message: "QR code not found or already expired",
          },
          404,
        );
      }

      await c.env.KV.delete(`qr:${token}`);

      const data = JSON.parse(qrData);

      console.log(
        `QR Code revoked by ${user.name} (${user.id}) - Token: ${token}`,
      );

      return c.json({
        success: true,
        message: "QR code revoked successfully",
        data: {
          token: token,
          location: data.locationName,
          type: data.type,
          revoked_by: user.name,
          revoked_at: new Date().toISOString(),
        },
      });
    } catch (error) {
      console.error("QR revoke error:", error);
      return c.json(
        {
          success: false,
          message: "Internal server error",
        },
        500,
      );
    }
  }

  /**
   * Generate multiple QR codes for all locations
   * Role: Admin only
   */
  static async generateForAllLocations(c: Context<{ Bindings: Env }>) {
    const user = c.get("user");
    const qrType = c.req.query("type") || "check_in";
    const db = createDb(c.env.DB);
    const cryptoHelper = new CryptoHelper(c.env);

    try {
      // Get all locations
      const allLocations = await db
        .select()
        .from(locations)
        .orderBy(locations.name);

      if (allLocations.length === 0) {
        return c.json(
          {
            success: false,
            message: "No locations found",
          },
          404,
        );
      }

      const generatedQRCodes = [];

      for (const location of allLocations) {
        const token = cryptoHelper.generateRandomToken(32);

        const qrData = {
          locationId: location.id.toString(),
          locationName: location.name,
          type: qrType,
          generatedBy: user.id,
          generatedByName: user.name,
          timestamp: new Date().toISOString(),
          expiresIn: 600,
        };

        await c.env.KV.put(`qr:${token}`, JSON.stringify(qrData), {
          expirationTtl: 600,
        });

        const qrCodeData = JSON.stringify({
          token: token,
          type: qrType,
          location_id: location.id,
        });

        const qrImageUrl = `https://api.qrserver.com/v1/create-qr-code/?data=${encodeURIComponent(qrCodeData)}&size=300x300&format=png`;

        generatedQRCodes.push({
          location_id: location.id,
          location_name: location.name,
          token: token,
          qr_code_url: qrImageUrl,
        });
      }

      return c.json({
        success: true,
        message: `Generated ${generatedQRCodes.length} QR codes`,
        data: {
          type: qrType,
          generated_by: {
            id: user.id,
            name: user.name,
          },
          expires_in: 600,
          qr_codes: generatedQRCodes,
        },
      });
    } catch (error) {
      console.error("Bulk QR generation error:", error);
      return c.json(
        {
          success: false,
          message: "Internal server error",
        },
        500,
      );
    }
  }

  /**
   * Get QR generation history (dari logs, implementasi sederhana)
   * Role: Admin only
   */
  static async history(c: Context<{ Bindings: Env }>) {
    const limit = c.req.query("limit") ? parseInt(c.req.query("limit")!) : 50;
    const offset = c.req.query("offset") ? parseInt(c.req.query("offset")!) : 0;

    try {
      // List all QR keys (untuk history sederhana)
      // Untuk production, lebih baik simpan di table terpisah
      const qrKeys = await c.env.KV.list({
        prefix: "qr:",
        limit: limit,
      });

      const history = [];

      for (const key of qrKeys.keys) {
        const qrData = await c.env.KV.get(key.name);
        if (qrData) {
          const data = JSON.parse(qrData);
          history.push({
            token: key.name.replace("qr:", ""),
            type: data.type,
            location: data.locationName,
            generated_by: data.generatedByName,
            generated_at: data.timestamp,
            status: "active", // Karena masih di KV berarti belum expired/digunakan
          });
        }
      }

      return c.json({
        success: true,
        data: {
          history: history,
          pagination: {
            limit,
            offset,
            total: history.length,
          },
        },
      });
    } catch (error) {
      console.error("QR history error:", error);
      return c.json(
        {
          success: false,
          message: "Internal server error",
        },
        500,
      );
    }
  }
}
